product = {
    "nom":"nom",
    "prix": 0,
    "Prix MRU":0*100,
    "Prix_de_vente": "",
    "Promo MRU":"",
    "Marque":"marque",
    "Id_Marque":"",
    'Categorie':"" 	,
    "Id_Categorie":"",
    "Fournisseur": "souq",	
    "Id_Fournissseur":"",
    "Référence": ""	,
    "Image":"xxx.jpg",	
    "Quantite":100, 	
    "Marge":"",	
    "Resume":"",	
    "Description":"desc", 	
    "lien":"lien",
}